#!/bin/sh
# preinst script for libwyliodrin
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#        * <old-preinst> `abort-upgrade' <new-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    install|upgrade)
	cd /tmp
	/usr/bin/wget https://github.com/Wyliodrin/wiringPi/archive/master.zip
	/usr/bin/unzip master.zip
	cd wiringPi-master
	./build
	cd /tmp
	/bin/rm -rf wiringPi-master master.zip
	/bin/ln -s /usr/bin/swig3.0 /usr/bin/swig && true
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
